Repository kubernetes-sigs/cloud-provider-huaweicloud, pull requests merged in 2020-07, with the labels that each got.

#75 Implement instanceID method
  go.sum
  pkg/cloudprovider/huaweicloud/huaweicloud.go
  pkg/cloudprovider/huaweicloud/instances.go
  pkg/cloudprovider/huaweicloud/instances_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#77 Fix example secret
  examples/loadbalancers/secret.yaml
  pkg/cloudprovider/huaweicloud/instances_test.go
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#79 Add issue template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#81 Add security file
  SECURITY.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S
