Repository kubernetes-sigs/cloud-provider-huaweicloud, pull requests merged in 2022-11, with the labels that each got.

#122 Put chengxiangdong to owner file
  OWNERS
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/XS

#123 fix checked parameter name
  hack/pre-run-e2e.sh
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/XS

#128 Fix a small typo in docs
  docs/quick-start-with-local-cluster.md
Labels: approved, lgtm, cncf-cla: yes, kind/documentation, size/XS

#126 Update endpoint from myhwclouds to myhuaweicloud
  pkg/cloudprovider/huaweicloud/config.go
  pkg/cloudprovider/huaweicloud/testdata/valid-cloud-provider.json
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/S

#124 add E2E test workflow
  .github/workflows/ci.yml
  hack/pre-run-e2e.sh
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/S

#131 fix logic issue in alb
  pkg/cloudprovider/huaweicloud/alb.go
Labels: approved, lgtm, cncf-cla: yes, size/XS

#132 Add Emacs and Vim related files to .gitignore
  .gitignore
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/S

#133 Fix nat gateway type of LoadBalancer
  pkg/cloudprovider/huaweicloud/nat.go
  pkg/cloudprovider/huaweicloud/nat_connections.go
Labels: kind/bug, approved, lgtm, cncf-cla: yes, size/S

#135 Add e2e test for dnat loadbalancer
  test/e2e/natlbservice_test.go
Labels: kind/feature, approved, lgtm, cncf-cla: yes, size/L

#136 Add update-gofmt.sh
  hack/update-gofmt.sh
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/S

#137 Update manifest for cloud-controller-manager
  docs/example-manifests/huawei-cloud-controller-manager.yaml
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/L

#130 Optimize Makefiles
  Makefile
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/XS

#125 optimize the image path in pre_run_e2e.sh
  hack/pre-run-e2e.sh
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/XS

#129 Set up E2E test not to run on forked repositories
  .github/workflows/ci.yml
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/XS

#113 Put the authentication credentials into the specified namespace
  examples/loadbalancers/secret.yaml
  hack/pre-run-e2e.sh
  pkg/cloudprovider/huaweicloud/alb.go
  pkg/cloudprovider/huaweicloud/elb.go
  pkg/cloudprovider/huaweicloud/huaweicloud.go
  pkg/cloudprovider/huaweicloud/nat.go
  test/e2e/loadbalancerservice_test.go
  test/e2e/natlbservice_test.go
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/L

#114 Fix the issue of calling K8s API with anonymous user
  pkg/cloudprovider/huaweicloud/huaweicloud.go
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/XS
