Repository kubernetes-sigs/cloud-provider-huaweicloud, pull requests merged in 2022-12, with the labels that each got.

#139 create common functions to make code more readable
  go.mod
  hack/verify-staticcheck.sh
  pkg/cloudprovider/huaweicloud/alb_connection.go
  pkg/cloudprovider/huaweicloud/elb_connection.go
  pkg/common/common.go
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/M

#141 Refactor Instance with huaweicloud-sdk-go-v3
  go.mod
  go.sum
  hack/pre-run-e2e.sh
  pkg/cloudprovider/huaweicloud/alb.go
  pkg/cloudprovider/huaweicloud/huaweicloud.go
  pkg/cloudprovider/huaweicloud/instances.go
  pkg/cloudprovider/huaweicloud/instances_test.go
  pkg/cloudprovider/huaweicloud/wrapper/ecs.go
  pkg/utils/filters.go
  pkg/utils/reflects.go
  pkg/utils/utils.go
  vendor/github.com/mitchellh/mapstructure/.travis.yml
  vendor/github.com/mitchellh/mapstructure/CHANGELOG.md
  vendor/github.com/mitchellh/mapstructure/LICENSE
  vendor/github.com/mitchellh/mapstructure/README.md
  vendor/github.com/mitchellh/mapstructure/decode_hooks.go
  vendor/github.com/mitchellh/mapstructure/error.go
  vendor/github.com/mitchellh/mapstructure/mapstructure.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL, cncf-cla: yes

#142 Add test for loadbalancerconfig
  pkg/config/loadbalancerconfig_test.go
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/L

#144 Add test for metadata
  pkg/utils/metadata/metadata_test.go
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/L

#145 move the util functions to its own module
  pkg/cloudprovider/huaweicloud/elb.go
  pkg/cloudprovider/huaweicloud/http.go
  pkg/cloudprovider/huaweicloud/huaweicloud.go
  pkg/cloudprovider/huaweicloud/nat.go
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/L

#146 update the name of config files or structs
  pkg/cloudprovider/huaweicloud/huaweicloud.go
  pkg/cloudprovider/huaweicloud/sharedloadbalancer.go
  pkg/cloudprovider/huaweicloud/wrapper/ecs.go
  pkg/cloudprovider/huaweicloud/wrapper/eip.go
  pkg/cloudprovider/huaweicloud/wrapper/shared_elb.go
  pkg/config/cloud.go
  pkg/config/config.go
  test/e2e/clients/eip.go
  test/e2e/clients/sharedelb.go
  test/e2e/suite_test.go
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/L

#148 Add test for utils/filters
  pkg/utils/filters_test.go
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/L

#150 init VpcOptions in suite_test
  test/e2e/loadbalancerservice_test.go
  test/e2e/suite_test.go
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/S

#147 create a basic top-level object for other providers to extend
  pkg/cloudprovider/huaweicloud/elb.go
  pkg/cloudprovider/huaweicloud/huaweicloud.go
  pkg/cloudprovider/huaweicloud/instances.go
  pkg/cloudprovider/huaweicloud/nat.go
  pkg/cloudprovider/huaweicloud/sharedloadbalancer.go
  pkg/config/loadbalancerconfig.go
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/L

#151 change "sendEvent" func to a Basic private func
  pkg/cloudprovider/huaweicloud/elb.go
  pkg/cloudprovider/huaweicloud/huaweicloud.go
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/M

#149 remove Config and use ConfigCloud instead in NAT and ELB services
  go.mod
  pkg/cloudprovider/huaweicloud/config.go
  pkg/cloudprovider/huaweicloud/config_test.go
  pkg/cloudprovider/huaweicloud/elb.go
  pkg/cloudprovider/huaweicloud/elb_connection.go
  pkg/cloudprovider/huaweicloud/huaweicloud.go
  pkg/cloudprovider/huaweicloud/nat.go
  pkg/cloudprovider/huaweicloud/nat_connections.go
  pkg/cloudprovider/huaweicloud/testdata/valid-cloud-provider.json
  test/signer/README.md
  test/signer/v4/main.go
Labels: kind/cleanup, approved, lgtm, size/XL, cncf-cla: yes

#152 add user-agent: huaweicloud-kubernetes-ccm to request header
  go.mod
  go.sum
  pkg/cloudprovider/huaweicloud/http.go
  pkg/config/config.go
  vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/core/hc_http_client.go
  vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/ecs/v2/ecs_meta.go
  vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/ecs/v2/model/model_list_servers_details_request.go
  vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/eip/v2/eip_client.go
  vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/eip/v2/eip_invoker.go
  vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/eip/v2/eip_meta.go
  vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/eip/v2/model/model_bw_change_to_period_req.go
  vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/eip/v2/model/model_change_bandwidth_to_period_request.go
  vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/eip/v2/model/model_change_bandwidth_to_period_response.go
  vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/eip/v2/model/model_change_publicip_to_period_request.go
  vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/eip/v2/model/model_change_publicip_to_period_response.go
  vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/eip/v2/model/model_change_to_period_req.go
  vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/eip/v2/model/model_show_resources_job_detail_request.go
  vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/eip/v2/model/model_show_resources_job_detail_response.go
  vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/eip/v2/model/model_sub_jobs.go
  vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/elb/v2/model/model_create_loadbalancer_req.go
  vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/elb/v2/model/model_list_loadbalancers_request.go
  vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/elb/v2/model/model_list_members_request.go
  vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/elb/v2/model/model_loadbalancer_resp.go
  vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/elb/v2/model/model_update_certificate_request_body.go
  vendor/github.com/huaweicloud/huaweicloud-sdk-go-v3/services/elb/v2/model/model_update_listener_req.go
  vendor/modules.txt
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/L

#154 change the event type to normal
  pkg/cloudprovider/huaweicloud/huaweicloud.go
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/XS

#155 add shared load balancer and deprecated union
  pkg/cloudprovider/huaweicloud/huaweicloud.go
  test/e2e/loadbalancerservice_test.go
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/XS

#156 add manifests files
  manifests/cloud-config
  manifests/huawei-cloud-controller-manager.yaml
  manifests/rbac-huawei-cloud-controller-manager.yaml
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/L

#157 update paramters name
  pkg/cloudprovider/huaweicloud/huaweicloud.go
  pkg/cloudprovider/huaweicloud/sharedloadbalancer.go
  pkg/config/loadbalancerconfig.go
  pkg/config/loadbalancerconfig_test.go
  test/e2e/loadbalancerservice_test.go
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/M

#158 Add test for utils/reflects
  pkg/utils/reflects_test.go
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/L

#159 Add test for utils
  pkg/utils/utils_test.go
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/M

#162 Update tests for utils pkg
  pkg/utils/utils_test.go
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/XS

#161 Add test for common pkg
  pkg/common/common_test.go
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/L

#153 add EndpointSliceListener to update the changed Endpoints to the ELB services
  pkg/cloudprovider/huaweicloud/huaweicloud.go
  pkg/utils/mutexkv/mutexkv.go
Labels: approved, lgtm, cncf-cla: yes, size/L

#165 Put niuzhenguo to owner file
  OWNERS
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/XS

#163 update loadbalancer examples
  examples/CloudControllerManagerConfigurationExample.json
  examples/loadbalancers/config.yaml
  examples/loadbalancers/deployment.yaml
  examples/loadbalancers/secret.yaml
  examples/loadbalancers/service-classic.yaml
  examples/loadbalancers/service-shared-autocreate.yaml
  examples/loadbalancers/service-shared-internal.yaml
  examples/loadbalancers/service_enhanced.yaml
  examples/loadbalancers/service_enhanced_auto.yaml
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/L

#166 update LoadbalancerConfig argument names
  pkg/cloudprovider/huaweicloud/elb.go
  pkg/cloudprovider/huaweicloud/huaweicloud.go
  pkg/cloudprovider/huaweicloud/nat.go
  pkg/cloudprovider/huaweicloud/sharedloadbalancer.go
  pkg/config/loadbalancerconfig.go
  pkg/config/loadbalancerconfig_test.go
  test/e2e/loadbalancerservice_test.go
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/L

#160 update docs
  README.md
  docs/config/CloudControllerManagerConfiguration.md
  docs/create-cloud-config-secret.md
  docs/example-manifests/etcd.yaml
  docs/example-manifests/huawei-cloud-controller-manager.yaml
  docs/example-manifests/kube-apiserver.yaml
  docs/example-manifests/kube-scheduler.yaml
  docs/getting-started.md
  docs/huawei-cloud-controller-manager-configuration.md
  docs/quick-start-with-local-cluster.md
  docs/resources/service/README.md
  docs/resources/service/annotations.md
  docs/usage-guide.md
Labels: approved, lgtm, size/XXL, cncf-cla: yes, kind/documentation
