Repository kubernetes-sigs/cloud-provider-huaweicloud, pull requests merged in 2023-01, with the labels that each got.

#164 add schedule on control-plane
  hack/pre-run-e2e.sh
  manifests/huawei-cloud-controller-manager.yaml
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/M

#168 add yaml that creates the huawei-cloud-provider namespace
  manifests/huawei-cloud-controller-manager.yaml
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/XS

#170 Sort the list of approvers and reviewers
  OWNERS
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/XS

#172 fix default value
  docs/usage-guide.md
Labels: approved, lgtm, cncf-cla: yes, kind/documentation, size/XS

#173 upgrade go-version to 1.19.x
  .github/workflows/swr-latest-image.yaml
  .github/workflows/swr-released-image.yaml
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/XS

#171 Remove unimplemented interfaces
  pkg/cloudprovider/huaweicloud/huaweicloud.go
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/M

#169 Update parameters name
  README.md
  docs/huawei-cloud-controller-manager-configuration.md
  docs/usage-guide.md
  pkg/cloudprovider/huaweicloud/huaweicloud.go
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/S

#175 Use the new registry org: k8s-cloudprovider
  Makefile
  hack/pre-run-e2e.sh
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/XS

#177 fix the issues that providerID in InstanceMetadata is empty
  pkg/cloudprovider/huaweicloud/instances.go
  pkg/utils/metadata/metadata.go
  pkg/utils/metadata/metadata_test.go
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/L

#183 fix the link issues
  docs/create-cloud-config-secret.md
  docs/huawei-cloud-controller-manager-configuration.md
  docs/usage-guide.md
Labels: approved, lgtm, cncf-cla: yes, kind/documentation, size/XS

#187 Fix docs description
  README.md
Labels: approved, lgtm, cncf-cla: yes, kind/documentation, size/XS

#186 Add latest version support for v1.25 and v1.26
  README.md
Labels: approved, lgtm, cncf-cla: yes, kind/documentation, size/XS

#188 Fix incorrect parameters and example data in documentation
  docs/huawei-cloud-controller-manager-configuration.md
  docs/usage-guide.md
Labels: approved, lgtm, cncf-cla: yes, size/S, kind/documentation

#189 Add default-tls-container-ref annotation to enable TERMINATED_HTTPS
  docs/usage-guide.md
  pkg/cloudprovider/huaweicloud/huaweicloud.go
  pkg/cloudprovider/huaweicloud/sharedloadbalancer.go
Labels: kind/feature, approved, lgtm, cncf-cla: yes, size/M

#191 add prefix "elb." to default-tls-container-ref
  docs/usage-guide.md
  pkg/cloudprovider/huaweicloud/huaweicloud.go
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/XS

#192 Update latest version
  README.md
Labels: approved, lgtm, cncf-cla: yes, size/S, kind/documentation
