Repository kubernetes-sigs/cloud-provider-huaweicloud, pull requests merged in 2023-05, with the labels that each got.

#217 Documentation Update for Clarifying the AZ annotation for multiple AZ
  docs/usage-guide.md
Labels: approved, lgtm, cncf-cla: yes, kind/documentation, size/XS

#219 Bump Kuberentes dependency to v1.26.4
  go.mod
  go.sum
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/apiserver/pkg/authentication/request/headerrequest/requestheader.go
  vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/create.go
  vendor/k8s.io/apiserver/pkg/registry/rest/rest.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/options/authentication.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/ready.go
  vendor/k8s.io/client-go/discovery/aggregated_discovery.go
  vendor/k8s.io/client-go/discovery/cached/memory/memcache.go
  vendor/k8s.io/client-go/discovery/discovery_client.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/delta_fifo.go
  vendor/k8s.io/client-go/tools/cache/shared_informer.go
  vendor/k8s.io/cloud-provider/cloud.go
  vendor/k8s.io/cloud-provider/controllers/route/route_controller.go
  vendor/k8s.io/controller-manager/app/serve.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/modules.txt
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/client.go
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/conn.go
Labels: kind/cleanup, approved, lgtm, size/XXL, cncf-cla: yes

#220 Fix typo in loadbalancerconfig.go
  pkg/config/loadbalancerconfig.go
Labels: kind/cleanup, approved, lgtm, cncf-cla: yes, size/XS

#221 Add description: CCM needs to be restarted after modifying the configurations
  docs/huawei-cloud-controller-manager-configuration.md
Labels: approved, lgtm, cncf-cla: yes, kind/documentation, size/XS
