Repository kubernetes-sigs/cloud-provider-huaweicloud, pull requests merged in 2024-01, with the labels that each got.

#237 A minor grammer suggestion
  README.md
Labels: approved, lgtm, cncf-cla: yes, size/XS

#239 feat: optimize repeatedly specifying EIP use case
  pkg/cloudprovider/huaweicloud/sharedloadbalancer.go
  pkg/cloudprovider/huaweicloud/wrapper/model/elb_meta.go
  pkg/cloudprovider/huaweicloud/wrapper/model/model_list_loadbalancers_rsp.go
  pkg/cloudprovider/huaweicloud/wrapper/model/model_loadbalancer.go
  pkg/cloudprovider/huaweicloud/wrapper/shared_elb.go
Labels: kind/feature, approved, cncf-cla: yes, size/L

#240 feat: add business-name to isolate ELB instances in multiple clusters
  docs/huawei-cloud-controller-manager-configuration.md
  pkg/cloudprovider/huaweicloud/dedicatedloadbalancer.go
  pkg/cloudprovider/huaweicloud/sharedloadbalancer.go
  pkg/config/loadbalancerconfig.go
Labels: kind/feature, approved, cncf-cla: yes, size/S

#241 feat: Add support for querying the primary network
  docs/huawei-cloud-controller-manager-configuration.md
  pkg/cloudprovider/huaweicloud/dedicatedloadbalancer.go
  pkg/cloudprovider/huaweicloud/huaweicloud.go
  pkg/cloudprovider/huaweicloud/model/ecs_meta.go
  pkg/cloudprovider/huaweicloud/model/model_list_servers_details_response.go
  pkg/cloudprovider/huaweicloud/model/model_server_address.go
  pkg/cloudprovider/huaweicloud/model/model_server_detail.go
  pkg/cloudprovider/huaweicloud/sharedloadbalancer.go
  pkg/cloudprovider/huaweicloud/wrapper/ecs.go
  pkg/config/loadbalancerconfig.go
  pkg/utils/utils.go
Labels: approved, lgtm, cncf-cla: yes, size/L
